name: kamn
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  fpdart: ^1.1.0
  get_it: ^8.0.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  uuid: ^4.4.0
  animate_do : ^3.3.4
  smooth_page_indicator: ^1.0.0+2
  gif: ^2.3.0
  rive: ^0.12.3
  animations: ^2.0.11
  flutter_animate: ^4.5.2
  fl_chart: ^0.69.0
  badges: ^3.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  permission_handler: ^10.0.0
  timezone: ^0.9.2
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.2.11
  firebase_core: ^3.3.0
  flutter_secure_storage: ^9.2.2
  flutter_image_slideshow: ^0.1.6
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^5.4.4
  dotted_border: ^2.1.0
  firebase_storage: ^12.3.4
  path: ^1.9.0
  flutter_image_compress: ^2.3.0
  location: ^7.0.1
  connectivity_plus: ^6.1.0
  injectable: ^2.5.0
  path_provider: ^2.1.5
  firebase_auth: ^5.3.3
  url_launcher: ^6.3.1
  flutter_countdown_timer: ^4.1.0
  table_calendar: ^3.1.2
  collection: ^1.17.0
  flutter_debouncer: ^2.0.0
  modal_bottom_sheet: ^3.0.0
  geolocator: ^13.0.2
  google_sign_in: ^6.2.2
  firebase_analytics: ^11.3.6
  firebase_remote_config: ^5.2.0
  firebase_crashlytics: ^4.2.0
  upgrader: ^11.3.1
  flutter_cache_manager: ^3.4.1
  dismissible_page: ^1.0.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - shorebird.yaml

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_28pt-Light.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        - asset: assets/fonts/Inter_28pt-Thin.ttf
        - asset: assets/fonts/Inter_28pt-Black.ttf
    - family: CircularSpotify
      fonts:
        - asset: assets/fonts/CircularSpotifyTxT-Bold.ttf
          weight: 700
        - asset: assets/fonts/CircularSpotifyTxT-Med.ttf
          weight: 500
        - asset: assets/fonts/CircularSpotifyTxT-Light.ttf
          weight: 300
        - asset: assets/fonts/CircularSpotifyTxT-Book.ttf
          weight: 400
